/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/operations/{id}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put API operations by ID classification */
        put: operations["put-api-operations-by-id-classification"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update operation overrides */
        put: operations["update-operation-overrides"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API projects */
        get: operations["list-api-projects"];
        put?: never;
        /** Post API projects */
        post: operations["post-api-projects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API projects by ID */
        get: operations["get-api-projects-by-id"];
        /** Put API projects by ID */
        put: operations["put-api-projects-by-id"];
        post?: never;
        /** Delete API projects by ID */
        delete: operations["delete-api-projects-by-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project-id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API projects by project ID runs */
        get: operations["list-api-projects-by-project-id-runs"];
        put?: never;
        /** Create and start a run */
        post: operations["create-run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project-id}/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import OpenAPI spec */
        post: operations["import-spec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID */
        get: operations["get-api-runs-by-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API runs by ID artifacts */
        get: operations["list-api-runs-by-id-artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API runs by ID comments */
        get: operations["list-api-runs-by-id-comments"];
        put?: never;
        /** Post API runs by ID comments */
        post: operations["post-api-runs-by-id-comments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/report/ci": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID report ci */
        get: operations["get-api-runs-by-id-report-ci"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/report/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID report debug */
        get: operations["get-api-runs-by-id-report-debug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/report/mermaid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID report mermaid */
        get: operations["get-api-runs-by-id-report-mermaid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID result */
        get: operations["get-api-runs-by-id-result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/specs/{spec-id}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API specs by spec ID operations */
        get: operations["list-api-specs-by-spec-id-operations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get health */
        get: operations["get-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Analysis: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/Analysis.json
             */
            readonly $schema?: string;
            operations: components["schemas"]["OperationInfo"][] | null;
            title: string;
            version: string;
        };
        Artifact: {
            created_at: components["schemas"]["Timestamptz"];
            id: components["schemas"]["UUID"];
            path: string;
            run_id: components["schemas"]["UUID"];
            type: string;
        };
        Assertion: {
            expected?: unknown;
            path?: string;
            type: string;
        };
        AuthProfile: {
            config: {
                [key: string]: unknown;
            };
            id: string;
            name: string;
            type: string;
        };
        CISummary: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/CISummary.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            duration_ms: number;
            /** Format: int64 */
            failed: number;
            failures?: string[] | null;
            /** Format: int64 */
            passed: number;
            status: string;
            /** Format: int64 */
            total: number;
        };
        Capture: {
            name: string;
            path: string;
            source: string;
        };
        Comment: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/Comment.json
             */
            readonly $schema?: string;
            author: string;
            body: string;
            created_at: components["schemas"]["Timestamptz"];
            id: components["schemas"]["UUID"];
            run_id: components["schemas"]["UUID"];
        };
        CreateCommentInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/CreateCommentInputBody.json
             */
            readonly $schema?: string;
            /** @description Comment author */
            author: string;
            /** @description Comment body */
            body: string;
        };
        CreateProjectInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/CreateProjectInputBody.json
             */
            readonly $schema?: string;
            /** @description Project description */
            description: string;
            /** @description Project name */
            name: string;
        };
        CreateRunInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/CreateRunInputBody.json
             */
            readonly $schema?: string;
            /** @description Compiled smoke plan to execute */
            plan: components["schemas"]["SmokePlan"];
            /** @description Plan UUID */
            plan_id: string;
        };
        DebugView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/DebugView.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            duration_ms: number;
            failures?: components["schemas"]["FailureInfo"][] | null;
            run_id: string;
            status: string;
            traces?: components["schemas"]["TraceInfo"][] | null;
        };
        Environment: {
            base_url: string;
            headers?: {
                [key: string]: string;
            };
            id: string;
            name: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FailureInfo: {
            assertion: string;
            message: string;
            request_url: string;
            /** Format: int64 */
            status: number;
            step: string;
        };
        FlowPlan: {
            cleanup?: components["schemas"]["PlannedStep"][] | null;
            flow_id: string;
            name: string;
            steps: components["schemas"]["PlannedStep"][] | null;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Service health status
             * @example ok
             */
            status: string;
        };
        Operation: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/Operation.json
             */
            readonly $schema?: string;
            classification: string;
            created_at: components["schemas"]["Timestamptz"];
            id: components["schemas"]["UUID"];
            is_destructive: boolean;
            method: string;
            operation_id: string;
            overrides: string;
            path: string;
            spec_id: components["schemas"]["UUID"];
            summary: string;
            tags: string;
        };
        OperationInfo: {
            classification: string;
            is_destructive: boolean;
            method: string;
            operation_id: string;
            path: string;
            summary: string;
            tags: string[] | null;
        };
        PlannedCase: {
            case_type: string;
            operation_id: string;
            step: components["schemas"]["PlannedStep"];
        };
        PlannedStep: {
            assertions?: components["schemas"]["Assertion"][] | null;
            body?: unknown;
            captures?: components["schemas"]["Capture"][] | null;
            headers?: {
                [key: string]: string;
            };
            method: string;
            name: string;
            params?: {
                [key: string]: unknown;
            };
            path: string;
        };
        Project: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/Project.json
             */
            readonly $schema?: string;
            created_at: components["schemas"]["Timestamptz"];
            description: string;
            id: components["schemas"]["UUID"];
            name: string;
            updated_at: components["schemas"]["Timestamptz"];
        };
        Run: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/Run.json
             */
            readonly $schema?: string;
            created_at: components["schemas"]["Timestamptz"];
            finished_at: components["schemas"]["Timestamptz"];
            id: components["schemas"]["UUID"];
            plan_id: components["schemas"]["UUID"];
            project_id: components["schemas"]["UUID"];
            started_at: components["schemas"]["Timestamptz"];
            status: string;
        };
        RunResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/RunResult.json
             */
            readonly $schema?: string;
            created_at: components["schemas"]["Timestamptz"];
            id: components["schemas"]["UUID"];
            result: string;
            run_id: components["schemas"]["UUID"];
        };
        SmokePlan: {
            auth?: components["schemas"]["AuthProfile"];
            /** Format: date-time */
            compiled_at: string;
            environment: components["schemas"]["Environment"];
            flow_plans?: components["schemas"]["FlowPlan"][] | null;
            id: string;
            project_id: string;
            suite_plans?: components["schemas"]["SuitePlan"][] | null;
        };
        SuitePlan: {
            cases: components["schemas"]["PlannedCase"][] | null;
            name: string;
            suite_id: string;
        };
        Timestamptz: {
            /** Format: int32 */
            InfinityModifier: number;
            /** Format: date-time */
            Time: string;
            Valid: boolean;
        };
        TraceInfo: {
            request_id?: string;
            step: string;
            trace_id?: string;
        };
        UUID: {
            Bytes: string;
            Valid: boolean;
        };
        UpdateClassificationInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/UpdateClassificationInputBody.json
             */
            readonly $schema?: string;
            /** @description Operation classification */
            classification: string;
            /** @description Whether operation is destructive */
            is_destructive: boolean;
        };
        UpdateProjectInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/UpdateProjectInputBody.json
             */
            readonly $schema?: string;
            /** @description Project description */
            description: string;
            /** @description Project name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "put-api-operations-by-id-classification": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClassificationInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-operation-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-projects-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-projects-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-api-projects-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-projects-by-project-id-runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                "project-id": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                "project-id": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "import-spec": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                "project-id": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-runs-by-id-artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-runs-by-id-comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-runs-by-id-comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id-report-ci": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CISummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id-report-debug": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id-report-mermaid": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id-result": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-specs-by-spec-id-operations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spec UUID */
                "spec-id": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
