/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/operations/{id}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put API operations by ID classification */
        put: operations["put-api-operations-by-id-classification"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update operation overrides */
        put: operations["update-operation-overrides"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API projects */
        get: operations["list-api-projects"];
        put?: never;
        /** Post API projects */
        post: operations["post-api-projects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API projects by ID */
        get: operations["get-api-projects-by-id"];
        /** Put API projects by ID */
        put: operations["put-api-projects-by-id"];
        post?: never;
        /** Delete API projects by ID */
        delete: operations["delete-api-projects-by-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project-id}/plan/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview compiled plan without persisting */
        post: operations["preview-plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project-id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API projects by project ID runs */
        get: operations["list-api-projects-by-project-id-runs"];
        put?: never;
        /** Create and start a run */
        post: operations["create-run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project-id}/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API projects by project ID specs */
        get: operations["list-api-projects-by-project-id-specs"];
        put?: never;
        /** Import OpenAPI spec from raw body */
        post: operations["import-spec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project-id}/specs/from-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import OpenAPI spec from URL */
        post: operations["import-spec-from-url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID */
        get: operations["get-api-runs-by-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API runs by ID artifacts */
        get: operations["list-api-runs-by-id-artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a running run */
        post: operations["cancel-run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API runs by ID comments */
        get: operations["list-api-runs-by-id-comments"];
        put?: never;
        /** Post API runs by ID comments */
        post: operations["post-api-runs-by-id-comments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/report/analyst": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID report analyst */
        get: operations["get-api-runs-by-id-report-analyst"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/report/ci": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID report ci */
        get: operations["get-api-runs-by-id-report-ci"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/report/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID report contract */
        get: operations["get-api-runs-by-id-report-contract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/report/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID report debug */
        get: operations["get-api-runs-by-id-report-debug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/report/mermaid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID report mermaid */
        get: operations["get-api-runs-by-id-report-mermaid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/report/qa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID report qa */
        get: operations["get-api-runs-by-id-report-qa"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API runs by ID result */
        get: operations["get-api-runs-by-id-result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/specs/{spec-id}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API specs by spec ID operations */
        get: operations["list-api-specs-by-spec-id-operations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check with DB and blob store probes */
        get: operations["health-check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Analysis: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/Analysis.json
             */
            readonly $schema?: string;
            operations: components["schemas"]["OperationInfo"][] | null;
            title: string;
            version: string;
        };
        AnalystView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/AnalystView.json
             */
            readonly $schema?: string;
            recommendations: components["schemas"]["Recommendation"][] | null;
            root_causes: components["schemas"]["RootCause"][] | null;
            run_id: string;
            summary: string;
            timeline_insights: components["schemas"]["TimelineInsight"][] | null;
        };
        Artifact: {
            /** Format: date-time */
            created_at: string;
            id: string;
            path: string;
            run_id: string;
            type: string;
        };
        Assertion: {
            expected?: unknown;
            path?: string;
            type: string;
        };
        AssertionResult: {
            actual?: unknown;
            expected?: unknown;
            message?: string;
            passed: boolean;
            type: string;
        };
        AuthProfile: {
            config: {
                [key: string]: unknown;
            };
            id: string;
            name: string;
            type: string;
        };
        CISummary: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/CISummary.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            duration_ms: number;
            /** Format: int64 */
            failed: number;
            failures?: string[] | null;
            /** Format: int64 */
            passed: number;
            status: string;
            /** Format: int64 */
            total: number;
        };
        Capture: {
            name: string;
            path: string;
            source: string;
        };
        CaseResult: {
            case_type: string;
            operation_id: string;
            step: components["schemas"]["StepResult"];
        };
        Comment: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/Comment.json
             */
            readonly $schema?: string;
            author: string;
            body: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            run_id: string;
        };
        ContractView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/ContractView.json
             */
            readonly $schema?: string;
            /** Format: double */
            compliance_score: number;
            errors: components["schemas"]["ContractViolation"][] | null;
            /** Format: int64 */
            failed_assertions: number;
            /** Format: int64 */
            passed_assertions: number;
            run_id: string;
            /** Format: int64 */
            total_violations: number;
            warnings: components["schemas"]["ContractViolation"][] | null;
        };
        ContractViolation: {
            actual_value?: unknown;
            expected_schema?: unknown;
            id: string;
            location: string;
            message: string;
            operation_id: string;
            severity: string;
            violation_type: string;
        };
        CoverageSummary: {
            /** Format: double */
            coverage_percentage: number;
            /** Format: int64 */
            tested_operations: number;
            /** Format: int64 */
            total_operations: number;
        };
        CreateCommentInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/CreateCommentInputBody.json
             */
            readonly $schema?: string;
            /** @description Comment author */
            author: string;
            /** @description Comment body */
            body: string;
        };
        CreateProjectInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/CreateProjectInputBody.json
             */
            readonly $schema?: string;
            /** @description Project description */
            description: string;
            /** @description Project name */
            name: string;
        };
        CreateRunInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/CreateRunInputBody.json
             */
            readonly $schema?: string;
            /** @description Compiled smoke plan to execute */
            plan: components["schemas"]["SmokePlan"];
            /** @description Plan UUID */
            plan_id: string;
        };
        DebugView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/DebugView.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            duration_ms: number;
            failures?: components["schemas"]["FailureInfo"][] | null;
            run_id: string;
            status: string;
            traces?: components["schemas"]["TraceInfo"][] | null;
        };
        Diagnostic: {
            code: string;
            entity_id?: string;
            entity_type?: string;
            location?: string;
            message: string;
            severity: string;
        };
        DiagnosticSummary: {
            is_compilable: boolean;
            /** Format: int64 */
            total_errors: number;
            /** Format: int64 */
            total_warnings: number;
        };
        Diagnostics: {
            errors?: components["schemas"]["Diagnostic"][] | null;
            summary: components["schemas"]["DiagnosticSummary"];
            warnings?: components["schemas"]["Diagnostic"][] | null;
        };
        EnumParam: {
            name: string;
            values: string[] | null;
        };
        Environment: {
            base_url: string;
            headers?: {
                [key: string]: string;
            };
            id: string;
            name: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FailureInfo: {
            assertion: string;
            message: string;
            request_url: string;
            /** Format: int64 */
            status: number;
            step: string;
        };
        Flow: {
            auth?: string;
            cleanup?: components["schemas"]["FlowStep"][] | null;
            description?: string;
            environment: string;
            id: string;
            name: string;
            steps: components["schemas"]["FlowStep"][] | null;
        };
        FlowPlan: {
            cleanup?: components["schemas"]["PlannedStep"][] | null;
            flow_id: string;
            name: string;
            steps: components["schemas"]["PlannedStep"][] | null;
        };
        FlowResult: {
            cleanup?: components["schemas"]["StepResult"][] | null;
            flow_id: string;
            name: string;
            status: string;
            steps: components["schemas"]["StepResult"][] | null;
        };
        FlowStep: {
            assertions?: components["schemas"]["Assertion"][] | null;
            body?: unknown;
            captures?: components["schemas"]["Capture"][] | null;
            headers?: {
                [key: string]: string;
            };
            name: string;
            operation_id: string;
            params?: {
                [key: string]: unknown;
            };
        };
        HealthDetailOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/HealthDetailOutputBody.json
             */
            readonly $schema?: string;
            /** @example ok */
            blob: string;
            /** @example ok */
            db: string;
            /** @example ok */
            status: string;
        };
        ImportSpecFromURLInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/ImportSpecFromURLInputBody.json
             */
            readonly $schema?: string;
            /** @description Custom headers for downloading (e.g. Authorization) */
            headers?: {
                [key: string]: string;
            };
            /** @description URL to download the OpenAPI spec from */
            url: string;
        };
        LastRunInfo: {
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            duration_ms: number;
            id: string;
            status: string;
        };
        Operation: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/Operation.json
             */
            readonly $schema?: string;
            classification: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            is_destructive: boolean;
            method: string;
            operation_id: string;
            overrides: string;
            path: string;
            spec_id: string;
            summary: string;
            tags: string[] | null;
        };
        OperationInfo: {
            classification: string;
            is_destructive: boolean;
            method: string;
            operation_id: string;
            path: string;
            query_hints?: components["schemas"]["QueryHints"];
            response_schema?: unknown;
            summary: string;
            tags: string[] | null;
        };
        PlanPreviewResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/PlanPreviewResponse.json
             */
            readonly $schema?: string;
            diagnostics: components["schemas"]["Diagnostics"];
            plan?: components["schemas"]["SmokePlan"];
        };
        PlannedCase: {
            case_type: string;
            empty_result_policy?: string;
            operation_id: string;
            step: components["schemas"]["PlannedStep"];
            steps?: components["schemas"]["PlannedStep"][] | null;
        };
        PlannedStep: {
            assertions?: components["schemas"]["Assertion"][] | null;
            body?: unknown;
            captures?: components["schemas"]["Capture"][] | null;
            headers?: {
                [key: string]: string;
            };
            method: string;
            name: string;
            params?: {
                [key: string]: unknown;
            };
            path: string;
            response_schema?: unknown;
        };
        Project: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/Project.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            description: string;
            id: string;
            name: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/ProjectConfig.json
             */
            readonly $schema?: string;
            auth_profiles: components["schemas"]["AuthProfile"][] | null;
            environments: components["schemas"]["Environment"][] | null;
            flows: components["schemas"]["Flow"][] | null;
            suites: components["schemas"]["Suite"][] | null;
        };
        ProjectHealthStats: {
            /** Format: int64 */
            env_count: number;
            /** Format: int64 */
            failed_runs: number;
            /** Format: int64 */
            flow_count: number;
            /** Format: double */
            health_percentage: number;
            /** Format: int64 */
            passed_runs: number;
            /** Format: int64 */
            suite_count: number;
            /** Format: int64 */
            total_runs: number;
        };
        ProjectWithStats: {
            /** Format: date-time */
            created_at: string;
            description: string;
            id: string;
            last_run?: components["schemas"]["LastRunInfo"];
            name: string;
            /** Format: int64 */
            spec_count: number;
            stats: components["schemas"]["ProjectHealthStats"];
            /** Format: date-time */
            updated_at: string;
        };
        QABlocker: {
            issue: string;
            operation_id: string;
            severity: string;
        };
        QAView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/QAView.json
             */
            readonly $schema?: string;
            blockers: components["schemas"]["QABlocker"][] | null;
            coverage_summary: components["schemas"]["CoverageSummary"];
            /** Format: int64 */
            failed_tests: number;
            flaky_tests: string[] | null;
            /** Format: double */
            pass_rate: number;
            /** Format: int64 */
            passed_tests: number;
            run_id: string;
            status: string;
            /** Format: int64 */
            total_tests: number;
        };
        QueryHints: {
            enum_filters?: components["schemas"]["EnumParam"][] | null;
            pagination_params?: string[] | null;
            search_params?: string[] | null;
        };
        Recommendation: {
            description: string;
            priority: string;
            title: string;
        };
        RequestMeta: {
            body?: unknown;
            headers?: {
                [key: string]: string;
            };
            method: string;
            url: string;
        };
        ResponseMeta: {
            body?: unknown;
            headers?: {
                [key: string]: string;
            };
            request_id?: string;
            /** Format: int64 */
            status: number;
            trace_id?: string;
        };
        RootCause: {
            affected_operations: string[] | null;
            cause: string;
            /** Format: int64 */
            impact: number;
        };
        Run: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/Run.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string;
            id: string;
            plan_id?: string;
            project_id: string;
            /** Format: date-time */
            started_at?: string;
            status: string;
        };
        RunMeta: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/RunMeta.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: int64 */
            fallback_poll_interval_ms: number;
            /** Format: date-time */
            finished_at?: string;
            id: string;
            plan_id?: string;
            project_id: string;
            /** Format: date-time */
            started_at?: string;
            status: string;
            websocket_url: string;
        };
        RunResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/RunResult.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            duration_ms: number;
            /** Format: date-time */
            finished_at: string;
            flows?: components["schemas"]["FlowResult"][] | null;
            run_id: string;
            /** Format: date-time */
            started_at: string;
            status: string;
            suites?: components["schemas"]["SuiteResult"][] | null;
        };
        SmokePlan: {
            auth?: components["schemas"]["AuthProfile"];
            /** Format: date-time */
            compiled_at: string;
            environment: components["schemas"]["Environment"];
            flow_plans?: components["schemas"]["FlowPlan"][] | null;
            id: string;
            project_id: string;
            suite_plans?: components["schemas"]["SuitePlan"][] | null;
        };
        Spec: {
            analysis: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            project_id: string;
            raw: string;
            title: string;
            version: string;
        };
        StepResult: {
            assertions: components["schemas"]["AssertionResult"][] | null;
            captures?: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            duration_ms: number;
            error?: string;
            name: string;
            request: components["schemas"]["RequestMeta"];
            response: components["schemas"]["ResponseMeta"];
            status: string;
        };
        Suite: {
            auth?: string;
            description?: string;
            environment: string;
            id: string;
            name: string;
            selector: components["schemas"]["SuiteSelector"];
            strategy: components["schemas"]["SuiteStrategy"];
        };
        SuitePlan: {
            cases: components["schemas"]["PlannedCase"][] | null;
            name: string;
            suite_id: string;
        };
        SuiteResult: {
            cases: components["schemas"]["CaseResult"][] | null;
            name: string;
            status: string;
            suite_id: string;
        };
        SuiteSelector: {
            classifications?: string[] | null;
            exclude?: string[] | null;
            paths?: string[] | null;
            tags?: string[] | null;
        };
        SuiteStrategy: {
            default_list: boolean;
            empty_result_policy: string;
            enum_filters: boolean;
            /** Format: int64 */
            max_cases_per_op?: number;
            pagination: boolean;
            search_from_response: boolean;
        };
        TimelineInsight: {
            /** Format: int64 */
            duration_ms: number;
            error?: string;
            operation_id: string;
            status: string;
            timestamp: string;
        };
        TraceInfo: {
            request_id?: string;
            step: string;
            trace_id?: string;
        };
        UpdateClassificationInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/UpdateClassificationInputBody.json
             */
            readonly $schema?: string;
            /** @description Operation classification */
            classification: string;
            /** @description Whether operation is destructive */
            is_destructive: boolean;
        };
        UpdateProjectInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example http://localhost:8080/schemas/UpdateProjectInputBody.json
             */
            readonly $schema?: string;
            /** @description Project description */
            description: string;
            /** @description Project name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "put-api-operations-by-id-classification": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClassificationInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-operation-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWithStats"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-projects-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-projects-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-api-projects-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "preview-plan": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                "project-id": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanPreviewResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-projects-by-project-id-runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                "project-id": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                "project-id": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-projects-by-project-id-specs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                "project-id": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Spec"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "import-spec": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                "project-id": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "import-spec-from-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                "project-id": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportSpecFromURLInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunMeta"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-runs-by-id-artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cancel-run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-runs-by-id-comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-runs-by-id-comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id-report-analyst": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalystView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id-report-ci": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CISummary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id-report-contract": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id-report-debug": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id-report-mermaid": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id-report-qa": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QAView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-runs-by-id-result": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-specs-by-spec-id-operations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spec UUID */
                "spec-id": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDetailOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
