// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (run_id, author, body) VALUES ($1, $2, $3) RETURNING id, run_id, author, body, created_at
`

type CreateCommentParams struct {
	RunID  pgtype.UUID `json:"run_id"`
	Author string      `json:"author"`
	Body   string      `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.RunID, arg.Author, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Author,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByRun = `-- name: ListCommentsByRun :many
SELECT id, run_id, author, body, created_at FROM comments WHERE run_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByRun(ctx context.Context, runID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
