// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (spec_id, operation_id, method, path, summary, tags, classification, is_destructive) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, spec_id, operation_id, method, path, summary, tags, classification, is_destructive, overrides, created_at
`

type CreateOperationParams struct {
	SpecID         pgtype.UUID `json:"spec_id"`
	OperationID    string      `json:"operation_id"`
	Method         string      `json:"method"`
	Path           string      `json:"path"`
	Summary        string      `json:"summary"`
	Tags           []byte      `json:"tags"`
	Classification string      `json:"classification"`
	IsDestructive  bool        `json:"is_destructive"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.SpecID,
		arg.OperationID,
		arg.Method,
		arg.Path,
		arg.Summary,
		arg.Tags,
		arg.Classification,
		arg.IsDestructive,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.SpecID,
		&i.OperationID,
		&i.Method,
		&i.Path,
		&i.Summary,
		&i.Tags,
		&i.Classification,
		&i.IsDestructive,
		&i.Overrides,
		&i.CreatedAt,
	)
	return i, err
}

const listOperationsBySpec = `-- name: ListOperationsBySpec :many
SELECT id, spec_id, operation_id, method, path, summary, tags, classification, is_destructive, overrides, created_at FROM operations WHERE spec_id = $1 ORDER BY path, method
`

func (q *Queries) ListOperationsBySpec(ctx context.Context, specID pgtype.UUID) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOperationsBySpec, specID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.SpecID,
			&i.OperationID,
			&i.Method,
			&i.Path,
			&i.Summary,
			&i.Tags,
			&i.Classification,
			&i.IsDestructive,
			&i.Overrides,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOperationClassification = `-- name: UpdateOperationClassification :one
UPDATE operations SET classification = $2, is_destructive = $3 WHERE id = $1 RETURNING id, spec_id, operation_id, method, path, summary, tags, classification, is_destructive, overrides, created_at
`

type UpdateOperationClassificationParams struct {
	ID             pgtype.UUID `json:"id"`
	Classification string      `json:"classification"`
	IsDestructive  bool        `json:"is_destructive"`
}

func (q *Queries) UpdateOperationClassification(ctx context.Context, arg UpdateOperationClassificationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, updateOperationClassification, arg.ID, arg.Classification, arg.IsDestructive)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.SpecID,
		&i.OperationID,
		&i.Method,
		&i.Path,
		&i.Summary,
		&i.Tags,
		&i.Classification,
		&i.IsDestructive,
		&i.Overrides,
		&i.CreatedAt,
	)
	return i, err
}

const updateOperationOverrides = `-- name: UpdateOperationOverrides :one
UPDATE operations SET overrides = $2 WHERE id = $1 RETURNING id, spec_id, operation_id, method, path, summary, tags, classification, is_destructive, overrides, created_at
`

type UpdateOperationOverridesParams struct {
	ID        pgtype.UUID `json:"id"`
	Overrides []byte      `json:"overrides"`
}

func (q *Queries) UpdateOperationOverrides(ctx context.Context, arg UpdateOperationOverridesParams) (Operation, error) {
	row := q.db.QueryRow(ctx, updateOperationOverrides, arg.ID, arg.Overrides)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.SpecID,
		&i.OperationID,
		&i.Method,
		&i.Path,
		&i.Summary,
		&i.Tags,
		&i.Classification,
		&i.IsDestructive,
		&i.Overrides,
		&i.CreatedAt,
	)
	return i, err
}
