// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (project_id, plan_id, status) VALUES ($1, $2, 'pending') RETURNING id, project_id, plan_id, status, started_at, finished_at, created_at
`

type CreateRunParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	PlanID    pgtype.UUID `json:"plan_id"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun, arg.ProjectID, arg.PlanID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PlanID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRunResult = `-- name: CreateRunResult :one
INSERT INTO run_results (run_id, result) VALUES ($1, $2) RETURNING id, run_id, result, created_at
`

type CreateRunResultParams struct {
	RunID  pgtype.UUID `json:"run_id"`
	Result []byte      `json:"result"`
}

func (q *Queries) CreateRunResult(ctx context.Context, arg CreateRunResultParams) (RunResult, error) {
	row := q.db.QueryRow(ctx, createRunResult, arg.RunID, arg.Result)
	var i RunResult
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, project_id, plan_id, status, started_at, finished_at, created_at FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PlanID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRunResult = `-- name: GetRunResult :one
SELECT id, run_id, result, created_at FROM run_results WHERE run_id = $1
`

func (q *Queries) GetRunResult(ctx context.Context, runID pgtype.UUID) (RunResult, error) {
	row := q.db.QueryRow(ctx, getRunResult, runID)
	var i RunResult
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const listRunsByProject = `-- name: ListRunsByProject :many
SELECT id, project_id, plan_id, status, started_at, finished_at, created_at FROM runs WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRunsByProject(ctx context.Context, projectID pgtype.UUID) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.PlanID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :one
UPDATE runs SET status = $2, started_at = $3, finished_at = $4 WHERE id = $1 RETURNING id, project_id, plan_id, status, started_at, finished_at, created_at
`

type UpdateRunStatusParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) (Run, error) {
	row := q.db.QueryRow(ctx, updateRunStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PlanID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
