// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: specs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpec = `-- name: CreateSpec :one
INSERT INTO specs (project_id, version, title, raw, analysis) VALUES ($1, $2, $3, $4, $5) RETURNING id, project_id, version, title, raw, analysis, created_at
`

type CreateSpecParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Version   string      `json:"version"`
	Title     string      `json:"title"`
	Raw       []byte      `json:"raw"`
	Analysis  []byte      `json:"analysis"`
}

func (q *Queries) CreateSpec(ctx context.Context, arg CreateSpecParams) (Spec, error) {
	row := q.db.QueryRow(ctx, createSpec,
		arg.ProjectID,
		arg.Version,
		arg.Title,
		arg.Raw,
		arg.Analysis,
	)
	var i Spec
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.Raw,
		&i.Analysis,
		&i.CreatedAt,
	)
	return i, err
}

const getSpec = `-- name: GetSpec :one
SELECT id, project_id, version, title, raw, analysis, created_at FROM specs WHERE id = $1
`

func (q *Queries) GetSpec(ctx context.Context, id pgtype.UUID) (Spec, error) {
	row := q.db.QueryRow(ctx, getSpec, id)
	var i Spec
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Title,
		&i.Raw,
		&i.Analysis,
		&i.CreatedAt,
	)
	return i, err
}

const listSpecsByProject = `-- name: ListSpecsByProject :many
SELECT id, project_id, version, title, raw, analysis, created_at FROM specs WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSpecsByProject(ctx context.Context, projectID pgtype.UUID) ([]Spec, error) {
	rows, err := q.db.Query(ctx, listSpecsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spec{}
	for rows.Next() {
		var i Spec
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.Title,
			&i.Raw,
			&i.Analysis,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
