// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (run_id, type, path) VALUES ($1, $2, $3) RETURNING id, run_id, type, path, created_at
`

type CreateArtifactParams struct {
	RunID pgtype.UUID `json:"run_id"`
	Type  string      `json:"type"`
	Path  string      `json:"path"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact, arg.RunID, arg.Type, arg.Path)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Type,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsByRun = `-- name: ListArtifactsByRun :many
SELECT id, run_id, type, path, created_at FROM artifacts WHERE run_id = $1 ORDER BY created_at
`

func (q *Queries) ListArtifactsByRun(ctx context.Context, runID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Type,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
