// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Artifact struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Type      string             `json:"type"`
	Path      string             `json:"path"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AuthProfile struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Config    []byte             `json:"config"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Author    string             `json:"author"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Environment struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	BaseUrl   string             `json:"base_url"`
	Headers   []byte             `json:"headers"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Flow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Operation struct {
	ID             pgtype.UUID        `json:"id"`
	SpecID         pgtype.UUID        `json:"spec_id"`
	OperationID    string             `json:"operation_id"`
	Method         string             `json:"method"`
	Path           string             `json:"path"`
	Summary        string             `json:"summary"`
	Tags           []byte             `json:"tags"`
	Classification string             `json:"classification"`
	IsDestructive  bool               `json:"is_destructive"`
	Overrides      []byte             `json:"overrides"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Plan struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	ConfigSnapshot []byte             `json:"config_snapshot"`
	CompiledPlan   []byte             `json:"compiled_plan"`
	Warnings       []byte             `json:"warnings"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Run struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	PlanID     pgtype.UUID        `json:"plan_id"`
	Status     string             `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RunResult struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Result    []byte             `json:"result"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Spec struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Version   string             `json:"version"`
	Title     string             `json:"title"`
	Raw       []byte             `json:"raw"`
	Analysis  []byte             `json:"analysis"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Suite struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
