package report

import (
	"fmt"
	"html/template"
	"strings"

	"github.com/fanboykun/smokery/apps/core/internal/model"
)

var htmlTmpl = template.Must(template.New("report").Parse(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Smoke Test Report — {{.RunID}}</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:system-ui,-apple-system,sans-serif;line-height:1.5;padding:2rem;max-width:960px;margin:0 auto;color:#1a1a1a}
h1{margin-bottom:.5rem}h2{margin-top:1.5rem;margin-bottom:.5rem}h3{margin-top:1rem}
.badge{display:inline-block;padding:.15rem .5rem;border-radius:4px;font-size:.8rem;font-weight:600;text-transform:uppercase}
.passed{background:#d4edda;color:#155724}.failed{background:#f8d7da;color:#721c24}
.error{background:#fff3cd;color:#856404}.cancelled{background:#e2e3e5;color:#383d41}
table{width:100%;border-collapse:collapse;margin:.5rem 0}
th,td{text-align:left;padding:.4rem .6rem;border-bottom:1px solid #dee2e6}
th{background:#f8f9fa;font-size:.85rem}
td{font-size:.85rem}
.mono{font-family:monospace;font-size:.8rem}
.summary{display:flex;gap:2rem;margin:1rem 0}
.summary-item{text-align:center}.summary-item .num{font-size:1.5rem;font-weight:700}
.assertion-msg{color:#721c24;font-size:.8rem}
</style>
</head>
<body>
<h1>Smoke Test Report</h1>
<p>Run ID: <code>{{.RunID}}</code> &mdash; <span class="badge {{.Status}}">{{.Status}}</span></p>
<div class="summary">
<div class="summary-item"><div class="num">{{.Total}}</div><div>Total</div></div>
<div class="summary-item"><div class="num" style="color:#155724">{{.Passed}}</div><div>Passed</div></div>
<div class="summary-item"><div class="num" style="color:#721c24">{{.Failed}}</div><div>Failed</div></div>
<div class="summary-item"><div class="num">{{.Duration}}ms</div><div>Duration</div></div>
</div>
{{range .Flows}}
<h2>Flow: {{.Name}} <span class="badge {{.Status}}">{{.Status}}</span></h2>
<table>
<tr><th>Step</th><th>Method</th><th>URL</th><th>Status</th><th>Duration</th><th>Result</th></tr>
{{range .Steps}}<tr>
<td>{{.Name}}</td><td>{{.Request.Method}}</td><td class="mono">{{.Request.URL}}</td>
<td>{{.Response.Status}}</td><td>{{.Duration}}ms</td>
<td><span class="badge {{.Status}}">{{.Status}}</span></td>
</tr>
{{range .Assertions}}{{if not .Passed}}<tr><td colspan="6" class="assertion-msg">⚠ {{.Type}}: {{.Message}}</td></tr>{{end}}{{end}}
{{end}}</table>
{{end}}
{{range .Suites}}
<h2>Suite: {{.Name}} <span class="badge {{.Status}}">{{.Status}}</span></h2>
<table>
<tr><th>Operation</th><th>Case</th><th>Method</th><th>Status</th><th>Duration</th><th>Result</th></tr>
{{range .Cases}}<tr>
<td>{{.OperationID}}</td><td>{{.CaseType}}</td><td>{{.Step.Request.Method}}</td>
<td>{{.Step.Response.Status}}</td><td>{{.Step.Duration}}ms</td>
<td><span class="badge {{.Step.Status}}">{{.Step.Status}}</span></td>
</tr>
{{range .Step.Assertions}}{{if not .Passed}}<tr><td colspan="6" class="assertion-msg">⚠ {{.Type}}: {{.Message}}</td></tr>{{end}}{{end}}
{{end}}</table>
{{end}}
<footer style="margin-top:2rem;font-size:.75rem;color:#6c757d">Generated by Smokery</footer>
</body>
</html>`))

type htmlData struct {
	RunID    string
	Status   string
	Total    int
	Passed   int
	Failed   int
	Duration int64
	Flows    []model.FlowResult
	Suites   []model.SuiteResult
}

// GenerateHTMLReport produces a self-contained HTML report from a RunResult.
func GenerateHTMLReport(result *model.RunResult) ([]byte, error) {
	data := htmlData{
		RunID:    result.RunID,
		Status:   result.Status,
		Duration: result.Duration,
		Flows:    result.Flows,
		Suites:   result.Suites,
	}
	for _, f := range result.Flows {
		for _, s := range f.Steps {
			data.Total++
			if s.Status == "passed" {
				data.Passed++
			} else {
				data.Failed++
			}
		}
	}
	for _, su := range result.Suites {
		for _, c := range su.Cases {
			data.Total++
			if c.Step.Status == "passed" {
				data.Passed++
			} else {
				data.Failed++
			}
		}
	}

	var sb strings.Builder
	if err := htmlTmpl.Execute(&sb, data); err != nil {
		return nil, fmt.Errorf("render html report: %w", err)
	}
	return []byte(sb.String()), nil
}
